"""is_active added

Revision ID: 2154d6a32cb7
Revises: b699e8e6f022
Create Date: 2026-05-23 00:21:19.281314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.database.tools import tashkent_now


# revision identifiers, used by Alembic.
revision: str = '2154d6a32cb7'
down_revision: Union[str, Sequence[str], None] = 'b699e8e6f022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kids', sa.Column('is_active', sa.Boolean(), default=True))
    op.add_column('kids', sa.Column('created_at', sa.DateTime(timezone=True), default=tashkent_now))
    op.alter_column('parents', 'phone_number',
               existing_type=sa.VARCHAR(length=90),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parents', 'phone_number',
               existing_type=sa.VARCHAR(length=90),
               nullable=True)
    op.drop_column('kids', 'created_at')
    op.drop_column('kids', 'is_active')
    # ### end Alembic commands ###
