"""phone_number deleted

Revision ID: 34a11c20f9f7
Revises: 
Create Date: 2026-06-07 15:26:30.286484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a11c20f9f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('phone_number', sa.VARCHAR(length=90), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
