"""null=True, routes

Revision ID: a30f46fcff3c
Revises: 34a11c20f9f7
Create Date: 2026-06-10 22:28:32.124791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a30f46fcff3c'
down_revision: Union[str, Sequence[str], None] = '34a11c20f9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('trips', 'departure_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('trips', 'arrival_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'arrival_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('trips', 'departure_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.add_column('attendance', sa.Column('schedule_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_schedule_id_fkey'), 'attendance', 'schedules', ['schedule_id'], ['id'])
    op.drop_index(op.f('ix_attendance_trip_id'), table_name='attendance')
    op.create_index(op.f('ix_attendance_schedule_id'), 'attendance', ['schedule_id'], unique=False)
    op.drop_column('attendance', 'trip_id')
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('route_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('departure_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='routestatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('schedules_route_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('schedules_pkey'))
    )
    op.create_index(op.f('ix_schedules_route_id'), 'schedules', ['route_id'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    # ### end Alembic commands ###
