"""routes

Revision ID: b7f0d0bfd1f7
Revises: a01a74239b2c
Create Date: 2026-05-06 23:46:27.957768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f0d0bfd1f7'
down_revision: Union[str, Sequence[str], None] = 'a01a74239b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=260), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('driver', sa.Integer(), nullable=False),
    sa.Column('babysitter', sa.Integer(), nullable=False),
    sa.Column('transport', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['babysitter'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['driver'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['transport'], ['transport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_babysitter'), 'routes', ['babysitter'], unique=False)
    op.create_index(op.f('ix_routes_driver'), 'routes', ['driver'], unique=False)
    op.create_index(op.f('ix_routes_duration'), 'routes', ['duration'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_transport'), 'routes', ['transport'], unique=False)
    op.add_column('kids', sa.Column('route', sa.Integer(), nullable=True))
    op.alter_column('kids', 'profile_picture',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
    op.create_index(op.f('ix_kids_route'), 'kids', ['route'], unique=False)
    op.create_foreign_key(None, 'kids', 'routes', ['route'], ['id'])
    op.alter_column('staff', 'profile_picture',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
    op.alter_column('transport', 'transport_picture',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transport', 'transport_picture',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
    op.alter_column('staff', 'profile_picture',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
    op.drop_constraint(None, 'kids', type_='foreignkey')
    op.drop_index(op.f('ix_kids_route'), table_name='kids')
    op.alter_column('kids', 'profile_picture',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
    op.drop_column('kids', 'route')
    op.drop_index(op.f('ix_routes_transport'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_duration'), table_name='routes')
    op.drop_index(op.f('ix_routes_driver'), table_name='routes')
    op.drop_index(op.f('ix_routes_babysitter'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
