"""routes fixed

Revision ID: f08b8bbb9aa2
Revises: b7f0d0bfd1f7
Create Date: 2026-05-06 23:54:33.677786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08b8bbb9aa2'
down_revision: Union[str, Sequence[str], None] = 'b7f0d0bfd1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kids', 'route',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kids', 'route',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
